// rope_unit: partial rotary embedding — bit-exact mirror of
// layer_fixed.rope_fx. Rotates the first ROT dims of an HD-element vector:
//   i < ROT/2:        y[i] = rshr(x[i]*cos[i] - x[i+ROT/2]*sin[i], 15)
//   ROT/2 <= i < ROT: y[i] = rshr(x[i]*cos[i] + x[i-ROT/2]*sin[i], 15)
//   i >= ROT:         y[i] = x[i]
// cos/sin tables (Q15, ROT entries) are HOST-PRECOMPUTED per position
// (generated by the python spec) and preloaded via the table port.
// Serial ~4 cycles/element after a full buffer fill.

`timescale 1ns/1ps
`default_nettype none

module rope_unit #(
    parameter int HD  = 256,
    parameter int ROT = 64
) (
    input  wire                clk,
    input  wire                rstn,
    input  wire                start,
    output logic               busy,

    // cos/sin preload: addr < ROT -> cos, addr >= ROT -> sin (addr-ROT)
    input  wire                t_we,
    input  wire [7:0]          t_waddr,
    input  wire [15:0]         t_wdata,

    input  wire                s_valid,
    output logic               s_ready,
    input  wire signed [15:0]  s_data,

    output logic               m_valid,
    input  wire                m_ready,
    output logic signed [15:0] m_data
);
    import fx_pkg::*;

    localparam int HROT = ROT / 2;

    logic signed [15:0] xbuf [HD];
    logic signed [15:0] cosb [ROT];
    logic signed [15:0] sinb [ROT];
    always_ff @(posedge clk) begin
        if (t_we) begin
            if (t_waddr < 8'(ROT)) cosb[t_waddr[5:0]] <= signed'(t_wdata);
            else                   sinb[t_waddr[5:0]] <= signed'(t_wdata);
        end
    end

    typedef enum logic [2:0] {IDLE, FILL, O_RD, O_MUL, O_EMIT} st_e;
    st_e st;
    logic [8:0] cnt, oidx;
    logic [1:0] wcnt;

    logic signed [15:0] x_q, rot_q, cos_q, sin_q;
    logic signed [33:0] p0a, p0b, pa, pb;
    always_ff @(posedge clk) begin
        p0a <= 34'(x_q) * 34'(cos_q);
        p0b <= 34'(rot_q) * 34'(sin_q);
        pa <= p0a;
        pb <= p0b;
    end

    assign s_ready = (st == FILL);

    always_ff @(posedge clk) begin
        if (!rstn) begin
            st <= IDLE;
            busy <= 1'b0;
            m_valid <= 1'b0;
        end else begin
            case (st)
                IDLE: if (start) begin
                    cnt <= '0;
                    busy <= 1'b1;
                    st <= FILL;
                end
                FILL: if (s_valid) begin
                    xbuf[cnt[7:0]] <= s_data;
                    cnt <= cnt + 1'b1;
                    if (cnt + 1'b1 == 9'(HD)) begin
                        oidx <= '0;
                        st <= O_RD;
                    end
                end
                O_RD: begin
                    if (oidx >= 9'(ROT)) begin
                        m_data <= xbuf[oidx[7:0]];      // passthrough
                        m_valid <= 1'b1;
                        st <= O_EMIT;
                    end else begin
                        x_q   <= xbuf[oidx[7:0]];
                        cos_q <= cosb[oidx[5:0]];
                        sin_q <= sinb[oidx[5:0]];
                        if (oidx < 9'(HROT)) begin
                            rot_q <= -xbuf[oidx[7:0] + 8'(HROT)];
                        end else begin
                            rot_q <= xbuf[oidx[7:0] - 8'(HROT)];
                        end
                        wcnt <= '0;
                        st <= O_MUL;
                    end
                end
                O_MUL: begin
                    wcnt <= wcnt + 1'b1;
                    if (wcnt == 2'd3) begin
                        m_data <= clip16(rshr64(64'(pa) + 64'(pb), 15));
                        m_valid <= 1'b1;
                        st <= O_EMIT;
                    end
                end
                O_EMIT: if (m_ready) begin
                    m_valid <= 1'b0;
                    oidx <= oidx + 1'b1;
                    if (oidx + 1'b1 == 9'(HD)) begin
                        busy <= 1'b0;
                        st <= IDLE;
                    end else
                        st <= O_RD;
                end
                default: st <= IDLE;
            endcase
        end
    end

endmodule

`default_nettype wire
