#!/usr/bin/env python3
"""seq_unit_vectors_check.py — does importing SCRATCH_WORDS move a TB vector?

    /home/cah/.venv/bin/python evidence/qwen9b/g2/seq_unit_vectors_check.py

`tb/scripts/gen_seq_unit_vectors.py` carried its own copy of the literal
`SCRATCH_WORDS = 32768`.  G2a made it an import from `sw/hwmap.py`, the
canonical definition — and in the same gate `sw/hwmap.SCRATCH_WORDS` moved
32,768 -> 65,536 for the spec §4.3 S4 array.  So the import is not a no-op:
the generator's behavioural scratchpad model doubles in depth.

That SHOULD be inert.  The generator only uses the constant to size
`Mach.mem`, and every address in these streams comes from
`ref/seq_format.py` under the 15-bit ISA, so no vector can name a word above
32,767.  "Should be" is not evidence, so this runs the real generator twice
per seed — once with `hwmap.SCRATCH_WORDS` forced back to 32,768, once as
imported — into two directories, and requires a byte-identical tree.

These vectors are REGENERATED by `make -C tb tb_seq` (the `seq_unit_vectors`
target), not committed, which is why the comparison has to be made here
rather than against a file in git.
"""
import filecmp
import os
import shutil
import subprocess
import sys
import tempfile

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                     "..", "..", ".."))
GEN = os.path.join(ROOT, "tb", "scripts", "gen_seq_unit_vectors.py")
SEEDS = (1, 2, 3, 4)                       # the campaign's 4-seed minimum


def run(td, tag, seed, force_old):
    out = os.path.join(td, tag)
    os.makedirs(out, exist_ok=True)
    shim = os.path.join(td, f"shim_{tag}.py")
    with open(shim, "w") as f:
        f.write(
            "import sys, os, runpy\n"
            f"sys.path.insert(0, os.path.join(r'{ROOT}', 'ref'))\n"
            f"sys.path.insert(0, os.path.join(r'{ROOT}', 'sw'))\n"
            "import hwmap as HW\n"
            + ("HW.SCRATCH_WORDS = 32768   # the pre-G2a literal\n"
               if force_old else "")
            + f"sys.argv = [r'{GEN}', r'{out}', '{seed}']\n"
            f"runpy.run_path(r'{GEN}', run_name='__main__')\n")
    r = subprocess.run([sys.executable, shim], capture_output=True,
                       text=True, cwd=ROOT)
    if r.returncode:
        print(r.stdout[-1200:])
        print(r.stderr[-1200:])
        sys.exit(f"generator failed at seed {seed} ({tag})")
    return out


def main():
    td = tempfile.mkdtemp(prefix="su_vec_")
    try:
        import importlib.util
        spec = importlib.util.spec_from_file_location(
            "hwmap", os.path.join(ROOT, "sw", "hwmap.py"))
        hw = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(hw)
        print(f"  sw/hwmap.SCRATCH_WORDS = {hw.SCRATCH_WORDS} "
              f"(pre-G2a literal: 32768)")
        for seed in SEEDS:
            a = run(td, "pre_fix", seed, True)
            b = run(td, "imported", seed, False)
        names = sorted(os.listdir(os.path.join(td, "imported")))
        match, mismatch, errors = filecmp.cmpfiles(
            os.path.join(td, "pre_fix"), os.path.join(td, "imported"),
            names, shallow=False)
        print(f"  seeds {list(SEEDS)}: {len(names)} artifacts, "
              f"{len(match)} identical, {len(mismatch)} differ, "
              f"{len(errors)} unreadable")
        for m in mismatch[:8]:
            print(f"    *** DIFFERS *** {m}")
        ok = not mismatch and not errors and names
        print("SEQ_UNIT_VECTORS " + ("PASS — importing SCRATCH_WORDS (and its "
                                     "32768 -> 65536 move) changed no vector "
                                     "byte"
                                     if ok else "FAIL"))
        return 0 if ok else 1
    finally:
        shutil.rmtree(td, ignore_errors=True)


if __name__ == "__main__":
    sys.exit(main())
