#!/usr/bin/env python3
"""sr4_r1_tdd.py — Task SR4 (sequencer RTL round): the R1 SOFTWARE side, test
first.  R1 = the FENCE channel mask (docs/SEQ_ISA.md v2.3 §B17.1: bit c of
target[3:0] = channel c; mask 0 = all four; a pending channel OUTSIDE the
mask stays pending; NO RTL interlock — the reference model's
RunningChannelError and reorder_e4's hazard assert are the only guard).

    FABLE5_MODEL=9b FABLE5_RS_F=7 /home/cah/.venv/bin/python \
        evidence/qwen9b/sr/sr4_r1_tdd.py

Run ON SNOKE through evidence/qwen9b/sr/sr_run.sh.  Cases (the plan's Task
SR4 step 1, docs/superpowers/plans/2026-09-27-seq-rtl-round.md):
  (a) the gate still catches the hazard under the new semantics: no-wait
      MVGO ch0 and ch1, FENCE mask=0b0010, MOVX ch0 -> RunningChannelError;
  (b) the same with MVGO, and with MOVY, in place of the MOVX;
  (c) FENCE mask=0b0011 then MOVX ch0 -> accepted;
  (d) mask 0 -> identical model state to today's FENCE;
  (e) reorder_e4.assert_no_pending_hazard raises HazardError on (a)'s order;
  (f) at r1 on reorder_e4._synthetic() (and on a two-channel synthetic where
      a mask can be a proper subset of the pending set) the emitted fences
      carry masks, the replay makespan is <= r0's, every emitted mask is a
      subset of the channels pending there; the output validates at
      caps={"R1"} and is refused at caps=empty; the manifest says
      seq_isa 2.3 / caps [R1] at r1 and nothing new at r0;
  (g) at r0 the output is byte-identical to today's: the form-A template pin
      (sw/chat_seq.py REORDER4_BY_FORM["A"], static costs) and SV1's CSV
      form-B pin of model_9b_s1 regenerate unchanged (the form-B per-image
      pins REORDER_B_IMAGES are regenerated by `sw/chat_seq.py --reorder B
      --reorder-check`, a separate log);
  (h) ref/seq_cost.py: a mask-{c} FENCE's poll tail is _tau(1)'s nearest-
      neighbour value over the MASKED group only; mask 0 unchanged.
Plus (i) the model is a software gate AT THE CAPS IT IS GIVEN: without "R1"
a masked FENCE is refused by the validator (today's rule).

RED fallback: if ref/seq_model.SeqExec has no `caps=` argument (the tree
before SR4), (a)-(d) run the model with seq_format.validate called at
caps={"R1"} by a wrapper, so what RED shows is the SEMANTIC gap (today's
FENCE clears every channel), not a TypeError.
"""
import hashlib
import inspect
import json
import os
import shutil
import sys
import tempfile
import traceback

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
for p in (os.path.join(REPO, "ref"), os.path.join(REPO, "ref", "scripts"),
          os.path.join(REPO, "sw"),
          os.path.join(REPO, "evidence", "qwen9b", "ov")):
    if p not in sys.path:
        sys.path.insert(0, p)

import numpy as np                           # noqa: E402
import seq_format as SF                      # noqa: E402
import seq_model as SM                       # noqa: E402
import seq_cost as SC                        # noqa: E402
import reorder_e4 as RE                      # noqa: E402
import gen_layer_script as GLS               # noqa: E402
import ov_census as OC                        # noqa: E402
import hwmap as HW                           # noqa: E402

R1 = frozenset({"R1"})
NONE = frozenset()
RESULTS = []


def check(tag, name, cond, detail=""):
    RESULTS.append((tag, bool(cond)))
    print(f"  [{'PASS' if cond else 'FAIL'}] ({tag}) {name}"
          + (f"  -- {detail}" if detail else ""))


def guarded(tag, name, fn):
    """Run fn() -> (cond, detail); an unexpected exception is a FAIL."""
    try:
        cond, detail = fn()
    except Exception as e:                   # noqa: BLE001
        cond, detail = False, f"{type(e).__name__}: {e}"
        traceback.print_exc(limit=3)
    check(tag, name, cond, detail)


# ======================================================================
# the model on synthetic streams (stub engine, as the model's own
# selftest_running_refusal does)
# ======================================================================
class _StubW(object):
    def matvec(self, wbase, nrows, sh, ng, g, x8, w8=False, chan=None):
        return np.arange(nrows, dtype=np.int64) + 7 * (chan or 0)

    def _lookup(self, wbase, chan=None):
        return 0, 0, {"stride": 64}, 0


NROWS = 4
SHAPE = HW.shape_word(NROWS, 0, 1)


def movx(c):
    return SF.Rec(SF.OP_MOVX, flags=(c << SF.CHAN_SHIFT), addr_lo=0,
                  len_or_addr_hi=128)


def mvgo(c):
    return SF.Rec(SF.OP_MVGO, flags=(c << SF.CHAN_SHIFT),
                  target=SF.MVGO_NOWAIT, imm32=SHAPE,
                  addr_lo=HW.W_BASE & 0xFFFFFFFF,
                  len_or_addr_hi=((NROWS << 8) | ((HW.W_BASE >> 32) & 0xFF)))


def movy(c, dst=256):
    return SF.Rec(SF.OP_MOVY, target=c, addr_lo=dst, len_or_addr_hi=NROWS)


def fence(mask=0):
    return SF.Rec(SF.OP_FENCE, target=mask)


HALT = SF.Rec(SF.OP_HALT)
HAS_CAPS = "caps" in inspect.signature(SM.SeqExec.__init__).parameters


def run_model(recs, caps):
    """-> the finished SeqExec.  Raises what the model raises."""
    if HAS_CAPS:
        return SM.SeqExec(list(recs), b"", _StubW(), caps=caps).run()
    real = SF.validate

    def at_caps(r, **k):
        k.setdefault("caps", caps)
        return real(r, **k)
    SF.validate = at_caps
    try:
        return SM.SeqExec(list(recs), b"", _StubW()).run()
    finally:
        SF.validate = real


def refused(recs, caps=R1):
    """-> (refused by RunningChannelError, detail)."""
    try:
        run_model(recs, caps)
        return False, "ACCEPTED (today's FENCE clears every channel)"
    except SM.RunningChannelError as e:
        return True, f"RunningChannelError: {e}"


def accepted(recs, caps=R1):
    ex = run_model(recs, caps)
    return True, f"accepted; running after = {sorted(ex.running)}"


def state_of(ex):
    return (sorted(ex.running), dict(ex.stats), SM.snapshot(ex.M),
            {c: np.asarray(v).tolist() for c, v in ex.xwin.items()},
            {c: np.asarray(v).tolist() for c, v in ex.res.items()})


def same_state(a, b):
    d = SM.diff_state(a[2], b[2])
    return (a[0] == b[0] and a[1] == b[1] and not d and a[3] == b[3]
            and a[4] == b[4]), d


def model_cases():
    print(f"=== the model (ref/seq_model.py), SeqExec caps= argument "
          f"{'PRESENT' if HAS_CAPS else 'ABSENT -> RED fallback wrapper'}")
    pre = [movx(0), mvgo(0), movx(1), mvgo(1)]
    # (a) + a channel-binding twin on 2/3 (bit c is channel c)
    guarded("a", "MVGO ch0+ch1, FENCE 0b0010, MOVX ch0 -> RunningChannelError",
            lambda: refused(pre + [fence(0b0010), movx(0), fence(0), HALT]))
    guarded("a", "twin on ch2/ch3: FENCE 0b1000 leaves ch2 -> MOVX ch2 refused",
            lambda: refused([movx(2), mvgo(2), movx(3), mvgo(3), fence(0b1000),
                             movx(2), fence(0), HALT]))
    # (b)
    guarded("b", "... FENCE 0b0010, MVGO ch0 -> RunningChannelError",
            lambda: refused(pre + [fence(0b0010), mvgo(0), fence(0), HALT]))
    guarded("b", "... FENCE 0b0010, MOVY ch0 -> RunningChannelError",
            lambda: refused(pre + [fence(0b0010), movy(0), fence(0), HALT]))
    guarded("b", "... FENCE 0b0001 (drains 0 only), MOVY ch1 -> refused",
            lambda: refused(pre + [fence(0b0001), movy(1), fence(0), HALT]))
    # (c)
    guarded("c", "FENCE 0b0011 then MOVX ch0 -> accepted",
            lambda: accepted(pre + [fence(0b0011), movx(0), movy(1), HALT]))
    guarded("c", "FENCE 0b0010 then MOVY ch1 (the drained one) -> accepted",
            lambda: accepted(pre + [fence(0b0010), movy(1), fence(0b0001),
                                    movy(0), HALT]))

    # (d) mask 0 == today's FENCE, and == mask 0b1111
    def d0():
        body = pre + [fence(0), movy(0, 256), movy(1, 512), movx(0), HALT]
        today = state_of(run_model(body, NONE))
        r1 = state_of(run_model(body, R1))
        ok, d = same_state(today, r1)
        return ok and today[0] == [], (f"running after {r1[0]}, "
                                       f"stats FENCE {r1[1]['FENCE']}, "
                                       f"state diff {d or 'none'}")
    guarded("d", "mask 0 under caps {R1}: state identical to today's FENCE", d0)

    def d1():
        a = pre + [fence(0), movy(0, 256), movy(1, 512), HALT]
        b = pre + [fence(0b1111), movy(0, 256), movy(1, 512), HALT]
        ok, d = same_state(state_of(run_model(a, R1)),
                           state_of(run_model(b, R1)))
        return ok, f"state diff {d or 'none'}"
    guarded("d", "mask 0b1111 drains exactly what mask 0 drains", d1)

    # (i) the model gate validates at the caps it is given
    def i0():
        try:
            SM.SeqExec(pre + [fence(0b0011), HALT], b"", _StubW()).run()
            return False, "a masked FENCE ran with no caps"
        except SF.SeqValidationError as e:
            return True, f"SeqValidationError: {e}"
    guarded("i", "caps empty: a masked FENCE is refused by the validator", i0)

    def i1():
        ok = "caps" in inspect.signature(SM.gate).parameters
        return ok, "gate(prefix, ..., caps=) " + ("present" if ok else "ABSENT")
    guarded("i", "ref/seq_model.gate takes caps= (sr4_gate.sh passes R1)", i1)


# ======================================================================
# the pass
# ======================================================================
def hazard_cases():
    print("=== the pass's hazard assert (ref/scripts/reorder_e4.py)")
    pre = [movx(0), mvgo(0), movx(1), mvgo(1)]

    def e(tail, want):
        recs = pre + tail
        try:
            RE.assert_no_pending_hazard(recs, "SR4")
            return (not want), "no HazardError"
        except RE.HazardError as x:
            return want, f"HazardError: {x}"
    guarded("e", "(a)'s order: FENCE 0b0010, MOVX ch0 -> HazardError",
            lambda: e([fence(0b0010), movx(0), fence(0), HALT], True))
    guarded("e", "FENCE 0b0010, MVGO ch0 -> HazardError",
            lambda: e([fence(0b0010), mvgo(0), fence(0), HALT], True))
    guarded("e", "FENCE 0b0010, MOVY ch0 -> HazardError",
            lambda: e([fence(0b0010), movy(0), fence(0), HALT], True))
    guarded("e", "FENCE 0b0010 then HALT with ch0 still pending -> HazardError",
            lambda: e([fence(0b0010), movy(1), HALT], True))
    guarded("e", "legal: FENCE 0b0010, MOVY ch1, FENCE 0b0001, MOVY ch0",
            lambda: e([fence(0b0010), movy(1), fence(0b0001), movy(0), HALT],
                      False))
    guarded("e", "legal: mask 0 still drains all four",
            lambda: e([fence(0), movx(0), movy(1), HALT], False))


def synthetic2():
    """Two channels: a SHORT stream on ch0 and a LONG one on ch1, one global
    FENCE; ch0's result feeds a long VN.  At r0 the VN waits for ch1's long
    stream; at r1 a FENCE 0b0001 lets it overlap it (a mask that is a
    PROPER subset of the pending set)."""
    def mx(c):
        return SF.Rec(SF.OP_MOVX, flags=(c << SF.CHAN_SHIFT), addr_lo=0x100,
                      len_or_addr_hi=128)

    def mg(c):
        return SF.Rec(SF.OP_MVGO, flags=(c << SF.CHAN_SHIFT),
                      target=SF.MVGO_NOWAIT, imm32=SHAPE,
                      addr_lo=HW.W_BASE & 0xFFFFFFFF,
                      len_or_addr_hi=(NROWS << 8))

    def my(c, dst):
        return SF.Rec(SF.OP_MOVY, flags=SF.MOVY_MODE_BIT, target=c,
                      addr_lo=dst, len_or_addr_hi=NROWS)

    def arg(t, v):
        return SF.Rec(SF.OP_CSRWR, target=t, imm32=v)
    recs = [
        SF.Rec(SF.OP_CSRWR, target=SF.CSR_SEQ_TCNT, imm32=2),   # 0
        SF.Rec(SF.OP_EMB, addr_lo=0x100, len_or_addr_hi=128),   # 1
        mx(0), mx(1),                                           # 2 3
        mg(0), mg(1),                                           # 4 5
        SF.Rec(SF.OP_FENCE),                                    # 6
        my(0, 0x400),                                           # 7
        arg(SF.CSR_L_ARG0, 6 << 2),                             # 8 VN x64
        arg(SF.CSR_L_ARG1, GLS.enc_a1(0x400, 0x900)),           # 9
        arg(SF.CSR_L_ARG2, 0),                                  # 10
        SF.Rec(SF.OP_CMD, imm32=1),                             # 11
        my(1, 0x500),                                           # 12
        SF.Rec(SF.OP_JMP, flags=SF.JMP_TCNT, imm32=1),          # 13
        SF.Rec(SF.OP_HALT),                                     # 14
    ]
    S = {4: (0, 200), 5: (1, 3000)}
    dur = {SF.OP_EMB: 200, SF.OP_MOVX: 100, SF.OP_MVGO: 10,
           SF.OP_MOVY: 50, SF.OP_CSRWR: 5, SF.OP_CMD: 2000, SF.OP_JMP: 3}
    rows, t, ends = {}, 0, []
    for pc in range(1, 14):
        o = recs[pc].opcode
        cls = [0] * 16
        if o == SF.OP_MVGO:
            c, s = S[pc]
            cls[OC.BSY0 + c] = s
            ends.append(t + dur[o] + s)
        d = (max(ends) + 40 - t) if o == SF.OP_FENCE else dur[o]
        rows[pc] = (o, t, d, cls)
        t += d
    return recs, rows, [[11, 0x400, 4]]


def pending_walk(recs):
    """-> (every FENCE mask non-empty and a subset of the pending channels,
    [mask per FENCE], detail)."""
    pend, masks, bad = set(), [], []
    for i, r in enumerate(recs):
        if r.opcode == SF.OP_MVGO and r.target & SF.MVGO_NOWAIT:
            pend.add(r.chan)
        elif r.opcode == SF.OP_FENCE:
            m = r.target & 0xF
            masks.append(m)
            chans = set(range(4)) if m == 0 else {c for c in range(4)
                                                   if (m >> c) & 1}
            if m == 0 or not chans <= pend:
                bad.append((i, m, sorted(pend)))
            pend -= chans
    return not bad, masks, (f"bad {bad[:3]}" if bad else "")


def refused_at_empty(recs):
    try:
        SF.validate_stream(recs)
        return False
    except SF.SeqValidationError:
        return True


def pass_cases():
    print("=== the pass at r1 (ref/scripts/reorder_e4.py --rtl r1)")
    has_rtl = "rtl" in inspect.signature(RE.reorder).parameters
    print(f"    reorder(..., rtl=) {'PRESENT' if has_rtl else 'ABSENT'}")
    for label, mk in (("_synthetic", lambda: RE._synthetic()),
                      ("synthetic2", synthetic2)):
        for form in ("A", "B"):
            def f(label=label, mk=mk, form=form):
                recs, rows, cps = mk()
                n0, _c0, r0 = RE.reorder(recs, lambda k, lo, hi: rows, form,
                                         cps, rtl="r0")
                recs, rows, cps = mk()
                n1, _c1, r1 = RE.reorder(recs, lambda k, lo, hi: rows, form,
                                         cps, rtl="r1")
                s0, s1 = r0["segments"][0], r1["segments"][0]
                ok_sub, masks, det = pending_walk(n1)
                carry = bool(masks) and all(m != 0 for m in masks)
                le = s1["replay_mk"] <= s0["replay_mk"]
                timed = 0 <= s1["replay_mk"] - s1["sched_mk"] <= s1["jmp_win"]
                SF.validate_stream(n1, caps=R1)
                ref0 = refused_at_empty(n1)
                RE.assert_no_pending_hazard(n1, "r1 OUTPUT")
                names = " ".join(
                    (f"FENCE/{r.target:04b}" if r.opcode == SF.OP_FENCE
                     else SF.OP_NAME[r.opcode]) for r in n1)
                strict = True
                if label == "synthetic2":
                    # the point of R1: a proper-subset mask, and a shorter
                    # makespan than the global drain
                    strict = (0b0001 in masks
                              and s1["replay_mk"] < s0["replay_mk"])
                ok = (ok_sub and carry and le and timed and ref0 and strict
                      and s1["post_replay"][0] > 0)
                return ok, (f"masks {[bin(m) for m in masks]}; replay r1 "
                            f"{s1['replay_mk']} <= r0 {s0['replay_mk']}: {le}; "
                            f"r1 replay - sched {s1['replay_mk'] - s1['sched_mk']}"
                            f" (JMP win {s1['jmp_win']}); valid at {{R1}}, "
                            f"refused at {{}}: {ref0}; postcheck "
                            f"{s1['post_replay'][0]} edges; {det} | {names}")
            guarded("f", f"{label} form {form}: masked fences, <= r0, masks "
                         f"within the pending set, R1-only valid", f)

    def manifest():
        recs, rows, cps = RE._synthetic()
        tmp = tempfile.mkdtemp(prefix="sr4_tdd_")
        try:
            src = os.path.join(tmp, "src.e4")
            stream = SF.pack_stream(recs)
            open(src + ".seq", "wb").write(stream)
            open(src + ".seqdata.bin", "wb").write(b"\0" * 64)
            json.dump({"stream_sha256": hashlib.sha256(stream).hexdigest(),
                       "nrec": len(recs)}, open(src + ".seq.json", "w"))
            got = {}
            for rtl in ("r0", "r1"):
                recs, rows, cps = RE._synthetic()
                new, ncps, rep = RE.reorder(recs, lambda k, lo, hi: rows, "B",
                                            cps, rtl=rtl)
                out = os.path.join(tmp, f"out_{rtl}.e4")
                RE.write_out(out, src, new, ncps, rep)
                m = json.load(open(out + ".seq.json"))
                got[rtl] = (m.get("seq_isa"), m.get("caps"))
            ok = got["r1"] == ("2.3", ["R1"]) and got["r0"] == (None, None)
            return ok, f"manifest (seq_isa, caps): {got}"
        finally:
            shutil.rmtree(tmp)
    guarded("f", "write_out: r1 records seq_isa 2.3 + caps [R1]; r0 nothing new",
            manifest)

    def refuse_masked_input():
        recs, rows, cps = synthetic2()
        recs[6] = SF.Rec(SF.OP_FENCE, target=0b0011)
        try:
            RE.reorder(recs, lambda k, lo, hi: rows, "B", cps, rtl="r1")
            return False, "reordered a stream that already carries masks"
        except RE.ReorderError as e:
            return True, f"ReorderError: {e}"
    guarded("f", "the pass refuses an input whose FENCEs are already masked "
                 "(OV1's stream_durations assumes the global drain)",
            refuse_masked_input)

    # SR11b fix round 1 (ownership granted for this case only): SR11b
    # landed --rtl r2, so the case that required it REFUSED is replaced 1:1
    # by its successor — r2 is accepted, its output validates at caps
    # {R1,R2} and is REFUSED at {R1} (an R1 bitstream ignores the banks,
    # SEQ_ISA v2.3 B17.2).
    def r2_admission():
        recs, rows, cps = RE._synthetic()
        new, _c, _rep = RE.reorder(recs, lambda k, lo, hi: rows, "B", cps,
                                   rtl="r2")
        SF.validate_stream(new, caps=frozenset({"R1", "R2"}))
        try:
            SF.validate_stream(new, caps=R1)
            return False, "the r2 output validated at {R1}"
        except SF.SeqValidationError as e:
            return True, (f"r2 accepted; valid at {{R1,R2}}; refused at "
                          f"{{R1}}: {e}")
    guarded("f", "--rtl r2 accepted (SR11b): valid at caps {R1,R2}, refused "
                 "at {R1}", r2_admission)


# ======================================================================
# (g) r0 byte-identical
# ======================================================================
SV1_S1_B_SHA = ("57ec3051a0d6e68ee689859bc020b440"
                "01bcce6323b8d5c78415055853bee4da")   # n32_reorder_s1_B.log:54


def r0_cases():
    print("=== r0: byte-identical to today's")
    has_rtl = "rtl" in inspect.signature(RE.reorder).parameters
    kw = {"rtl": "r0"} if has_rtl else {}

    def synth():
        outs = []
        for form in ("A", "B"):
            recs, rows, cps = RE._synthetic()
            a = RE.reorder(recs, lambda k, lo, hi: rows, form, cps)
            recs, rows, cps = RE._synthetic()
            b = RE.reorder(recs, lambda k, lo, hi: rows, form, cps, **kw)
            outs.append(SF.pack_stream(a[0]) == SF.pack_stream(b[0])
                        and a[1] == b[1]
                        and all(r.target == 0 for r in b[0]
                                if r.opcode == SF.OP_FENCE))
        return all(outs), f"forms A/B default == explicit r0: {outs}"
    guarded("g", "_synthetic: the default IS r0, every FENCE target 0", synth)

    def pin_a():
        import chat_seq as CS
        parts, sha, nrec, _log = CS.REORDER4_BY_FORM["A"]
        src = CS.TEMPLATE4_PREFIX
        stream = open(src + ".seq", "rb").read()
        meta = json.load(open(src + ".seq.json"))
        recs = SF.unpack_stream(stream)
        new, _c, rep = RE.reorder(recs, SC.rows_for(recs), "A",
                                  meta.get("checkpoints", []), **kw)
        got = hashlib.sha256(SF.pack_stream(new)).hexdigest()
        return (got == sha and len(new) == nrec,
                f"regenerated {got[:16]} ({len(new)} recs), pin {sha[:16]} "
                f"({nrec})")
    guarded("g", "form A template (static costs) == REORDER4_BY_FORM['A'] pin",
            pin_a)

    def pin_csv():
        src = os.path.join(REPO, "tb", "scripts", "w9", "model_9b_s1.e4")
        stream = open(src + ".seq", "rb").read()
        meta = json.load(open(src + ".seq.json"))
        recs = SF.unpack_stream(stream)
        new, _c, rep = RE.reorder(recs, RE.rows_provider("csv", recs), "B",
                                  meta.get("checkpoints", []), **kw)
        got = hashlib.sha256(SF.pack_stream(new)).hexdigest()
        disk = hashlib.sha256(open(os.path.join(
            REPO, "tb", "scripts", "w9", "model_9b_s1_reordB.e4.seq"),
            "rb").read()).hexdigest()
        return (got == SV1_S1_B_SHA == disk,
                f"regenerated {got[:16]}, SV1 pin {SV1_S1_B_SHA[:16]}, "
                f"on disk {disk[:16]}")
    guarded("g", "model_9b_s1 form B, CSV costs == SV1's shipped reordB "
                 "(n32)", pin_csv)


# ======================================================================
# (h) the static cost model
# ======================================================================
def cost_cases():
    print("=== the static cost model (ref/seq_cost.py)")

    def mg(c, beats):
        return SF.Rec(SF.OP_MVGO, flags=(c << SF.CHAN_SHIFT),
                      target=SF.MVGO_NOWAIT, imm32=SHAPE, addr_lo=0,
                      len_or_addr_hi=(beats << 8))
    bs0, bs1 = 1024, 8448
    s0 = SC._lin(SC.STREAM, bs0)
    s1 = SC._lin(SC.STREAM, bs1)

    def seg(masks):
        recs = [mg(0, bs0), mg(1, bs1)]
        recs += [SF.Rec(SF.OP_FENCE, target=m) for m in masks]
        return SC.cost_of_segment(recs, 0, len(recs) - 1, 0)
    t_after = 2 * SC.MVGO                       # both MVGO issue windows
    end0 = SC.MVGO + s0                         # ch0's stream end
    end1 = 2 * SC.MVGO + s1                     # ch1's stream end

    def h1():
        rows = seg([0b0001, 0b0010])
        f1, f2 = rows[2], rows[3]
        want1 = max(end0 + SC._tau(1), t_after + 1) - t_after
        want2 = max(end1 + SC._tau(1), f1[1] + f1[2] + 1) - (f1[1] + f1[2])
        return (f1[2] == want1 and f2[2] == want2 and SC._tau(1) == 61,
                f"FENCE 0b0001 row {f1[2]} (want {want1} = ch0 end {end0} + "
                f"_tau(1) {SC._tau(1)} - {t_after}); FENCE 0b0010 row {f2[2]} "
                f"(want {want2})")
    guarded("h", "mask {c}: the tail is _tau(1) (nearest neighbour = size 2, "
                 "61) over the MASKED stream only", h1)

    def h2():
        rows = seg([0])
        want = end1 + SC._tau(2) - t_after
        return rows[2][2] == want, f"FENCE 0 row {rows[2][2]} (want {want})"
    guarded("h", "mask 0: unchanged (both streams, _tau(2))", h2)

    def h3():
        return (SC._tau(3) == SC.TAU[2] and SC._tau(1) == SC.TAU[2],
                f"_tau(1) {SC._tau(1)}, _tau(3) {SC._tau(3)} (TAU {SC.TAU}; "
                "a tie takes the smaller size)")
    guarded("h", "sizes 1 and 3 are nearest-neighbour (documented)", h3)

    def h4():
        doc = SC.__doc__ + (SC._tau.__doc__ or "")
        ok = "masked" in doc.lower() and "1 and 3" in doc
        return ok, "docstring names the masked group and sizes 1 and 3"
    guarded("h", "seq_cost docstring records the masked group", h4)


def main():
    print(f"=== sr4_r1_tdd.py  FABLE5_MODEL={os.environ.get('FABLE5_MODEL')} "
          f"FABLE5_RS_F={os.environ.get('FABLE5_RS_F')}")
    model_cases()
    hazard_cases()
    pass_cases()
    cost_cases()
    r0_cases()
    by = {}
    for tag, ok in RESULTS:
        by.setdefault(tag, []).append(ok)
    print("=== per case: " + "  ".join(
        f"({t}) {sum(v)}/{len(v)}" for t, v in sorted(by.items())))
    failed = sorted(t for t, v in by.items() if not all(v))
    npass = sum(ok for _t, ok in RESULTS)
    print(f"=== {npass} passed, {len(RESULTS) - npass} failed; failing cases: "
          f"{failed or 'none'}")
    print("SR4 R1 TDD: " + ("PASS" if not failed else "FAIL"))
    raise SystemExit(0 if not failed else 1)


if __name__ == "__main__":
    main()
