#!/usr/bin/env python3
"""scan_spare_bits.py — prove which ISA bits are SPARE across every stream.

Track R task R-b widens the layer scratchpad from 16K to 32K words, which
means every scratch address field in the layer command ISA and in the SEQ
record ISA needs a 15th bit.  There is no room to grow a field in place, so
each new bit-14 rides in a bit of the SAME record that is PROVEN NEVER SET
by any stream that already exists.  That proof is what this script produces:

  * for every LAYER command opcode (1..12) it OR-accumulates ARG0/ARG1/ARG2
    over every `C` record of every committed/derived .txt script AND over
    every layer command reconstructed from the binary SEQ streams (a SEQ
    CSRWR to layer 0x08/0x0C/0x10 loads the ARG shadow; the following CMD
    record dispatches it);
  * for every SEQ opcode it OR-accumulates flags / target / imm32 /
    addr_lo / len_or_addr_hi over every 16-byte record;
  * for the layer CSR space it OR-accumulates the value written to each
    CSR offset (this is where SPTR's width claim is checked).

A bit that is 0 in the OR mask was never set by ANY stream, so giving it a
new meaning cannot change how any of those streams replay.  The table of
WIDENED-FIELD homes — R-b's bit-14 scratch addresses and R-c's bit 12 of
the ALU element count — is encoded at the bottom and CHECKED against the
masks: the script exits non-zero if any chosen home was ever set.

WHAT IT MUST BE POINTED AT.  The claim is about the LEGACY (pre-R-b)
streams — the ones whose back-compatibility the widening had to preserve.
Post-R-b streams legitimately SET the new bits (that is the whole point of
`tb/scripts/seqlayer_s*.txt`), so scanning them would report the new usage
as a conflict and make the tool useless as a regression check.  The frozen
legacy set is therefore listed explicitly in LEGACY_STREAMS below and is
the DEFAULT; `--all` scans everything (useful for inspection, expected to
"fail" the verdict), and explicit ROOTs override both.

Usage:  python3 ref/scripts/scan_spare_bits.py [--out FILE] [--all] [ROOT ...]
Exit code: 0 if every chosen widened-field home is spare across the set.
"""
import argparse
import os
import struct
import sys

# ----------------------------------------------------------------- names
LAYER_OPS = {
    1: "VN", 2: "VNW", 3: "ROPET", 4: "ROPE", 5: "CONVW", 6: "CONV",
    7: "GATE", 8: "DNST", 9: "KVAP", 10: "ATTN", 11: "ALU", 12: "DNZ",
}
SEQ_OPS = {
    0x01: "CSRWR", 0x02: "CMD", 0x03: "MOVX", 0x04: "MOVY", 0x05: "MVGO",
    0x06: "EMB", 0x07: "AMAXL", 0x08: "JMP", 0x09: "FENCE", 0x0A: "HALT",
    0x0B: "LDC", 0x0C: "XOP",
}
# layer_chan CSR byte offsets (rtl/layer_chan.sv:12-31)
LAYER_CSR = {
    0x00: "CMD", 0x08: "ARG0", 0x0C: "ARG1", 0x10: "ARG2", 0x14: "SPTR",
    0x18: "SWIN", 0x20: "TCNT", 0x30: "LAYER", 0x34: "LCYC", 0x38: "XRFI",
    0x3C: "XRFD", 0x50: "TK_PTR",
}

# ---------------------------------------------------------------------
# The FROZEN PRE-R-b STREAM SET.  These are exactly the artifacts the
# widening promised to keep replaying bit-identically (docs/SEQ_ISA.md
# B12), and they are the only ones whose bit usage is evidence about what
# was spare BEFORE R-b.  Anything regenerated by a post-R-b emitter is
# deliberately excluded — see the module docstring.
#
# EXCLUDED, and why:
#   seqlayer_s*.txt  the R-b directed >16K case itself; it SETS the new
#                    bits by construction (that is what it tests).
# Everything else under tb/scripts is either in the list below or a
# regenerable derivative of something that is.
LEGACY_STREAMS = [
    "tb/scripts/layer_s1.txt", "tb/scripts/layer_s2.txt",
    "tb/scripts/layer_s3.txt", "tb/scripts/layer_s4.txt",
    "tb/scripts/token_s1.txt", "tb/scripts/token_s2.txt",
    "tb/scripts/token_s3.txt", "tb/scripts/token_s4.txt",
    "tb/scripts/chain_s1.txt", "tb/scripts/chain_s2.txt",
    "tb/scripts/chain_s3.txt", "tb/scripts/chain_s4.txt",
    "tb/scripts/token24_s1.txt", "tb/scripts/token24_s2.txt",
    "tb/scripts/token24_s3.txt", "tb/scripts/token24_s4.txt",
    "tb/scripts/model_s1.txt", "tb/scripts/model_s2.txt",
    "tb/scripts/model_s3.txt", "tb/scripts/model_s4.txt",
    "tb/scripts/model_rs8_s1.txt", "tb/scripts/model_rs8_s2.txt",
    "tb/scripts/model_rs8_s3.txt", "tb/scripts/model_rs8_s4.txt",
    "tb/scripts/model_g64_s1.txt",
    "tb/scripts/model_v2_s1.txt", "tb/scripts/model_v2_s2.txt",
    "tb/scripts/model_v2_s3.txt", "tb/scripts/model_v2_s4.txt",
    "tb/scripts/w3",            # lay_s1 / tok2_s1 .txt + .e.seq
    "tb/scripts/w4",            # model_v2_s1 .txt + .e.seq, chat_i1{,b}.seq
]

REC = struct.Struct("<IIII")


class Acc:
    """OR-accumulator with a per-key hit count."""

    def __init__(self):
        self.mask = {}
        self.hits = {}

    def add(self, key, vals):
        m = self.mask.setdefault(key, [0] * len(vals))
        for i, v in enumerate(vals):
            m[i] |= int(v) & 0xFFFFFFFF
        self.hits[key] = self.hits.get(key, 0) + 1


def free_bits(mask, width=32):
    """Bit indices never set, as a compact range string."""
    free = [b for b in range(width) if not (mask >> b) & 1]
    if not free:
        return "(none)"
    out, i = [], 0
    while i < len(free):
        j = i
        while j + 1 < len(free) and free[j + 1] == free[j] + 1:
            j += 1
        out.append(str(free[i]) if i == j else f"{free[j]}:{free[i]}")
        i = j + 1
    return ",".join(reversed(out))


# ------------------------------------------------------------- scanning
def scan_txt(path, lay, csr_unused):
    """Layer command scripts: `C <op> <a0> <a1> <a2>` in hex."""
    n = 0
    with open(path, "r") as f:
        for line in f:
            if not line.startswith("C "):
                continue
            p = line.split()
            if len(p) != 5:
                continue
            op = int(p[1], 16)
            lay.add(op, (int(p[2], 16), int(p[3], 16), int(p[4], 16)))
            n += 1
    return n


def scan_seq(path, lay, seq, csr):
    """Binary SEQ records; also replays the ARG shadow to recover the layer
    commands the stream dispatches (seq_unit.sv:949-954 does exactly this)."""
    with open(path, "rb") as f:
        blob = f.read()
    if len(blob) % REC.size:
        raise SystemExit(f"{path}: not a multiple of {REC.size} bytes")
    a0 = a1 = a2 = 0
    nrec = 0
    for off in range(0, len(blob), REC.size):
        w0, imm, lo, hi = REC.unpack_from(blob, off)
        op, flags, tgt = w0 & 0xFF, (w0 >> 8) & 0xFF, (w0 >> 16) & 0xFFFF
        seq.add(op, (flags, tgt, imm, lo, hi))
        nrec += 1
        if op == 0x01 and (tgt >> 12) == 0:          # CSRWR into layer space
            csr.add(tgt & 0xFF, (imm,))
            if (tgt & 0xFF) == 0x08:
                a0 = imm
            elif (tgt & 0xFF) == 0x0C:
                a1 = imm
            elif (tgt & 0xFF) == 0x10:
                a2 = imm
        elif op == 0x02 and (tgt >> 12) == 0:        # CMD macro
            csr.add(tgt & 0xFF, (imm,))
            lay.add(imm & 0xF, (a0, a1, a2))
    return nrec


def walk(roots):
    txts, seqs = [], []
    for r in roots:
        if os.path.isfile(r):
            (seqs if r.endswith(".seq") else txts).append(r)
            continue
        for dirpath, _dirs, files in os.walk(r):
            for fn in sorted(files):
                p = os.path.join(dirpath, fn)
                if fn.endswith(".txt"):
                    txts.append(p)
                elif fn.endswith(".seq"):
                    seqs.append(p)
    return sorted(txts), sorted(seqs)


# ------------------------------------------------- the widened-bit table
# (opcode, word, bit, what it now carries).  word 0/1/2 = ARG0/ARG1/ARG2.
#
# Rows tagged R-c are the SECOND widening this table has carried: the ALU
# element count.  `ARG0 = {len[15:4], aop[3:0]}` gave `rtl/vec_alu.sv` a
# 12-bit `cfg_len`, which tops out at 4095 — and the Qwen3.5-2B MLP
# quantizes its whole FFN = 6144 intermediate in ONE DYNQ8, a length that
# cannot be chunked (one shared exponent over the vector, reported on
# EOUT).  The count therefore grows to `arg0[16:4]`, 13 bits, and bit 16 is
# the home this scan has to prove spare.  It is the same argument R-b made
# for the scratch addresses, and the same evidence: a bit never set by any
# frozen stream can be given a meaning without changing how they replay.
#
# NOTE this scan reads the binary `.seq` streams as well as the `.txt`
# scripts, which matters here specifically: `ref/seq_format.py` SYNTHESIZES
# ALU commands of its own (the attention EMUL32 probe pair, the fused
# matvec dequant, the AMAX32 chunks, DYNQ16) that never appear in a `.txt`.
# A `.txt`-only scan would have missed them entirely.
LAYER_HOMES = [
    (1,  1, 28, "VN    src[14]      (arg1[13:0]  src)"),
    (1,  1, 29, "VN    dst[14]      (arg1[27:14] dst)"),
    (2,  1, 28, "VNW   src[14]"),
    (3,  1, 28, "ROPET src[14]"),
    (4,  1, 28, "ROPE  src[14]"),
    (4,  1, 29, "ROPE  dst[14]"),
    (5,  1, 28, "CONVW src[14]"),
    (6,  1, 28, "CONV  src[14]"),
    (6,  1, 29, "CONV  dst[14]"),
    (7,  0, 14, "GATE  dst[14]      (arg0[13:0] -> arg0[14:0])"),
    (7,  1, 28, "GATE  src_b[14]"),
    (7,  1, 29, "GATE  src_a[14]"),
    (7,  2, 28, "GATE  src_A[14]"),
    (7,  2, 29, "GATE  src_dt[14]"),
    (8,  1, 28, "DNST  src_q[14]"),
    (8,  1, 29, "DNST  src_k[14]"),
    (8,  1, 30, "DNST  a_dec[14]    (re-pack: arg0 is full)"),
    (8,  1, 31, "DNST  a_beta[14]   (re-pack: arg0 is full)"),
    (8,  2, 28, "DNST  src_v[14]"),
    (8,  2, 29, "DNST  dst[14]"),
    (9,  1, 28, "KVAP  src_k[14]"),
    (9,  1, 29, "KVAP  src_v[14]"),
    (10, 1, 28, "ATTN  src_q[14]"),
    (10, 1, 29, "ATTN  dst[14]"),
    (11, 1, 28, "ALU   srca[14]"),
    (11, 1, 29, "ALU   srcb[14]"),
    (11, 2, 31, "ALU   dst[14]      (arg2[30:17] dst, bit31 is the ONLY spare)"),
    (11, 0, 16, "ALU   len[12]      (R-c: arg0[15:4] -> arg0[16:4], 12->13b)"),
]
# (seq opcode, field index, bit, what it now carries).  Field indices are
# 0 flags, 1 target, 2 imm32, 3 addr_lo, 4 len_or_addr_hi.
SEQ_HOMES = [
    (0x03, 3, 14, "MOVX  scratch src[14]  (addr_lo[14])"),
    (0x04, 3, 14, "MOVY  scratch dst[14]  (addr_lo[14])"),
    (0x06, 3, 14, "EMB   scratch dst[14]  (addr_lo[14])"),
    (0x0B, 1, 14, "LDC   scratch dst[14]  (target[14])"),
]
# layer CSR offset, bit, meaning (SPTR grows [13:0] -> [14:0])
CSR_HOMES = [
    (0x14, 14, "SPTR  wdata[14]  (CSR, host/mover-written)"),
]
FIELD_NAMES = ["flags", "target", "imm32", "addr_lo", "len_hi"]
ARG_NAMES = ["ARG0", "ARG1", "ARG2"]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("roots", nargs="*", default=None)
    ap.add_argument("--out", default=None)
    ap.add_argument("--all", action="store_true",
                    help="scan ALL of tb/scripts, post-R-b streams included "
                         "(inspection only — the verdict is expected to "
                         "report the new bits as SET)")
    args = ap.parse_args()

    here = os.path.dirname(os.path.abspath(__file__))
    repo = os.path.abspath(os.path.join(here, "..", ".."))
    if args.roots:
        roots = args.roots
        scope = "explicit"
    elif args.all:
        roots = [os.path.join(repo, "tb", "scripts")]
        scope = "ALL of tb/scripts (post-R-b included — inspection only)"
    else:
        roots = [os.path.join(repo, r) for r in LEGACY_STREAMS]
        roots = [r for r in roots if os.path.exists(r)]
        scope = "the frozen PRE-R-b stream set (LEGACY_STREAMS)"

    lay, seq, csr = Acc(), Acc(), Acc()
    txts, seqs = walk(roots)
    files = []
    for p in txts:
        files.append((p, "txt", scan_txt(p, lay, csr)))
    for p in seqs:
        files.append((p, "seq", scan_seq(p, lay, seq, csr)))

    out = []
    w = out.append
    w("=== R-b spare-bit scan — which ISA bits are EVER set in a stream ===")
    w("")
    w(f"Scope: {scope}")
    w("Roots: " + ", ".join(os.path.relpath(r, repo) for r in roots))
    w(f"Files scanned: {len(txts)} layer .txt scripts, {len(seqs)} SEQ .seq "
      f"record streams")
    w("")
    for p, kind, n in files:
        w(f"  {kind}  {os.path.relpath(p, repo):<44} {n:>8d} records")
    w("")
    w("A bit that is 0 in the OR mask below was never set by ANY of these")
    w("streams, so giving it a new meaning cannot change how any of them")
    w("replays.  'free' lists exactly those bits.")
    w("")

    w("--- LAYER command args (opcode -> OR of ARG0/1/2 over every C) ---")
    w(f"{'op':<12}{'n':>9}  {'word':<6}{'OR mask':<12}{'free bits'}")
    for op in sorted(lay.mask):
        name = LAYER_OPS.get(op, f"?{op}")
        m = lay.mask[op]
        for i in range(3):
            head = f"{op:>2} {name:<9}{lay.hits[op]:>9}  " if i == 0 \
                else " " * 23
            w(f"{head}{ARG_NAMES[i]:<6}{m[i]:#010x}  {free_bits(m[i])}")
    w("")

    w("--- SEQ record fields (opcode -> OR of each field over every record) -")
    w(f"{'op':<12}{'n':>9}  {'field':<8}{'OR mask':<12}{'free bits'}")
    for op in sorted(seq.mask):
        name = SEQ_OPS.get(op, f"?{op:#x}")
        m = seq.mask[op]
        for i in range(5):
            head = f"{op:#04x} {name:<7}{seq.hits[op]:>9}  " if i == 0 \
                else " " * 23
            width = 8 if i == 0 else (16 if i == 1 else 32)
            w(f"{head}{FIELD_NAMES[i]:<8}{m[i]:#010x}  {free_bits(m[i], width)}")
    if not seq.mask:
        w("  (no SEQ streams found)")
    w("")

    w("--- layer CSR writes made by SEQ streams (offset -> OR of the value) -")
    w(f"{'off':<8}{'name':<10}{'n':>9}  {'OR mask':<12}{'free bits'}")
    for off in sorted(csr.mask):
        nm = LAYER_CSR.get(off, "?")
        w(f"{off:#04x}    {nm:<10}{csr.hits[off]:>9}  "
          f"{csr.mask[off][0]:#010x}  {free_bits(csr.mask[off][0])}")
    if not csr.mask:
        w("  (no SEQ streams found)")
    w("")

    # ---------------------------------------------------------- verdict
    bad = []
    w("=== the widened-field home table (R-b bit-14, R-c ALU len[12]), "
      "checked against the masks ===")
    w("")
    w("LAYER commands:")
    w(f"  {'op':<10}{'word':<6}{'bit':<5}{'was it ever set?':<20}carries")
    for op, word, bit, note in LAYER_HOMES:
        m = lay.mask.get(op, [0, 0, 0])[word]
        hit = bool((m >> bit) & 1)
        if hit:
            bad.append(f"layer op {op} {ARG_NAMES[word]} bit {bit}")
        w(f"  {LAYER_OPS[op]:<10}{ARG_NAMES[word]:<6}{bit:<5}"
          f"{'*** SET ***' if hit else 'never set':<20}{note}")
    w("")
    w("SEQ records:")
    w(f"  {'op':<10}{'field':<9}{'bit':<5}{'was it ever set?':<20}carries")
    for op, fld, bit, note in SEQ_HOMES:
        m = seq.mask.get(op, [0] * 5)[fld]
        hit = bool((m >> bit) & 1)
        if hit:
            bad.append(f"seq op {op:#x} {FIELD_NAMES[fld]} bit {bit}")
        w(f"  {SEQ_OPS[op]:<10}{FIELD_NAMES[fld]:<9}{bit:<5}"
          f"{'*** SET ***' if hit else 'never set':<20}{note}")
    w("")
    w("layer CSR:")
    w(f"  {'off':<10}{'name':<9}{'bit':<5}{'was it ever set?':<20}carries")
    for off, bit, note in CSR_HOMES:
        m = csr.mask.get(off, [0])[0]
        hit = bool((m >> bit) & 1)
        if hit:
            bad.append(f"layer CSR {off:#x} bit {bit}")
        w(f"  {off:#04x}      {LAYER_CSR.get(off, '?'):<9}{bit:<5}"
          f"{'*** SET ***' if hit else 'never set':<20}{note}")
    w("")
    if bad:
        w("SCAN VERDICT: FAIL — these chosen homes are NOT spare:")
        for b in bad:
            w("  " + b)
    else:
        w("SCAN VERDICT: PASS — every chosen bit-14 home is 0 in every "
          "scanned stream.")
    w("")
    w("CAVEAT — a row can pass VACUOUSLY.  'never set' is evidence only")
    w("where the field is actually exercised: an opcode with 0 records, or")
    w("a CSR offset never written by any scanned stream, trivially reports")
    w("every bit free.  Check the record count beside each opcode before")
    w("leaning on its row.  The layer SPTR CSR (0x14) is the one home in")
    w("the table with NO in-stream writer today — the movers program SPTR")
    w("over AXI-Lite, not through a CSRWR record — so its row is vacuous:")
    w("SPTR's back-compatibility rests on it being a HOST-written CSR whose")
    w("bit 14 the old RTL simply ignored, not on this scan.")

    text = "\n".join(out) + "\n"
    if args.out:
        os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
        with open(args.out, "w") as f:
            f.write(text)
        print(text, end="")
        print(f"(written to {args.out})")
    else:
        print(text, end="")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
